name: Build library

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - "nodemcuv2"
          - "lolin32"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install 3rd party dependencies
      run: |
        pio lib install \
        ArduinoJson \
        FastLED \
        LinkedList \
        WebSockets \
        https://github.com/tzapu/WiFiManager \
        https://github.com/srwi/ESPEssentials
    - name: Create main file
      run: |
        echo "#include <Arduino.h>" >> main.ino
        echo "void setup() { }" >> main.ino
        echo "void loop() { }" >> main.ino
    - name: Run PlatformIO
      run: pio ci --board=${{ matrix.board }} .
